version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: Agent-Alpha
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - VERTEX_AI_EMAIL=${VERTEX_AI_EMAIL}
      - VERTEX_AI_PRIVATE_KEY=${VERTEX_AI_PRIVATE_KEY}
    volumes:
      - ./n8n:/home/node/.n8n